### ISSUE TITLE
[Bug] Make sure cache is properly loaded in the GitHub Workflow

### ISSUE THREAD

**Issue by Hybris95** [Hybris95/UEX-Trader#61]
Env job is properly working but when using the other jobs like test and build, cache is "loaded" but is not reflected in pip environment.
Make sure pip is properly using the cache so the jobs take less time overall.

**Comment by Hybris95** [comment]
Test to do with following solution :
https://adamj.eu/tech/2023/11/02/github-actions-faster-python-virtual-environments/

```yaml
# ...

jobs:
  example:
    # ...

    steps:
      # ...

      - uses: actions/setup-python@v5
        id: setup_python
        with:
          python-version: '3.12'

      - name: Restore cached virtualenv
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          path: .venv

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

      - name: Saved cached virtualenv
        uses: actions/cache/save@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          path: .venv

      # ...
```
